// TRANG THAI THEM MOI
export const ALERT_ON_TRANGTHAITHEMMOITHANHCONG = 'ALERT_ON_TRANGTHAITHEMMOITHANHCONG';
export const ALERT_OFF_TRANGTHAITHEMMOITHANHCONG = 'ALERT_OFF_TRANGTHAITHEMMOITHANHCONG';
export const ALERT_ON_TRANGTHAITHEMMOITHATBAI = 'ALERT_ON_TRANGTHAITHEMMOITHATBAI';
export const ALERT_OFF_TRANGTHAITHEMMOITHATBAI = 'ALERT_OFF_TRANGTHAITHEMMOITHATBAI';
// TRANG THAI SUA
export const ALERT_ON_TRANGTHAISUATHANHCONG = 'ALERT_ON_TRANGTHAISUATHANHCONG';
export const ALERT_OFF_TRANGTHAISUATHANHCONG = 'ALERT_OFF_TRANGTHAISUATHANHCONG';
export const ALERT_ON_TRANGTHAISUATHATBAI = 'ALERT_ON_TRANGTHAISUATHATBAI';
export const ALERT_OFF_TRANGTHAISUATHATBAI = 'ALERT_OFF_TRANGTHAISUATHATBAI';
// TRANG THAI XOA
export const ALERT_ON_TRANGTHAIXOATHANHCONG = 'ALERT_ON_TRANGTHAIXOATHANHCONG';
export const ALERT_OFF_TRANGTHAIXOATHANHCONG = 'ALERT_OFF_TRANGTHAIXOATHANHCONG';
export const ALERT_ON_TRANGTHAIXOATHATBAI = 'ALERT_ON_TRANGTHAIXOATHATBAI';
export const ALERT_OFF_TRANGTHAIXOATHATBAI = 'ALERT_OFF_TRANGTHAIXOATHATBAI';
// TRANG THAI DUYET
export const ALERT_ON_TRANGTHAIDUYETTHANHCONG = 'ALERT_ON_TRANGTHAIDUYETTHANHCONG';
export const ALERT_OFF_TRANGTHAIDUYETTHANHCONG = 'ALERT_OFF_TRANGTHAIDUYETTHANHCONG';
export const ALERT_ON_TRANGTHAIDUYETTHATBAI = 'ALERT_ON_TRANGTHAIDUYETTHATBAI';
export const ALERT_OFF_TRANGTHAIDUYETTHATBAI = 'ALERT_OFF_TRANGTHAIDUYETTHATBAI';
// TRANG THAI TU CHOI DUYET
export const ALERT_ON_TRANGTHAITUCHOIDUYETTHANHCONG = 'ALERT_ON_TRANGTHAITUCHOIDUYETTHANHCONG';
export const ALERT_OFF_TRANGTHAITUCHOIDUYETTHANHCONG = 'ALERT_OFF_TRANGTHAITUCHOIDUYETTHANHCONG';
export const ALERT_ON_TRANGTHAITUCHOIDUYETTHATBAI = 'ALERT_ON_TRANGTHAITUCHOIDUYETTHATBAI';
export const ALERT_OFF_TRANGTHAITUCHOIDUYETTHATBAI = 'ALERT_OFF_TRANGTHAITUCHOIDUYETTHATBAI';
// TRANG THAI THANH TOAN
export const ALERT_ON_TRANGTHAITHANHTOANTHANHCONG = 'ALERT_ON_TRANGTHAITHANHTOANTHANHCONG';
export const ALERT_OFF_TRANGTHAITHANHTOANTHANHCONG = 'ALERT_OFF_TRANGTHAITHANHTOANTHANHCONG';
export const ALERT_ON_TRANGTHAITHANHTOANTHATBAI = 'ALERT_ON_TRANGTHAITHANHTOANTHATBAI';
export const ALERT_OFF_TRANGTHAITHANHTOANTHATBAI = 'ALERT_OFF_TRANGTHAITHANHTOANTHATBAI';
// TRANG THAI QUYEN
export const ALERT_ON_TRANGTHAIQUYENTHANHCONG = 'ALERT_ON_TRANGTHAIQUYENTHANHCONG';
export const ALERT_OFF_TRANGTHAIQUYENTHANHCONG = 'ALERT_OFF_TRANGTHAIQUYENTHANHCONG';
export const ALERT_ON_TRANGTHAIQUYENTHATBAI = 'ALERT_ON_TRANGTHAIQUYENTHATBAI';
export const ALERT_OFF_TRANGTHAIQUYENTHATBAI = 'ALERT_OFF_TRANGTHAIQUYENTHATBAI';
